name: DevSecOps Pipeline

on:
  push:
    paths: ['project-3-devsecops-pipeline/**']
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Scan
        working-directory: ./project-3-devsecops-pipeline
        run: |
          # Build
          docker build -t myapp .
          
          # Scan
          trivy image --severity HIGH,CRITICAL myapp
          
          # Test
          docker run --rm myapp python -c "print('âœ… App works!')"