name: Build Todo App

on:
  push:
    paths: ['project-1-todo-app/**']
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker Image
        working-directory: ./project-1-todo-app
        continue-on-error: true
        run: |
          docker build -t todo-app .
          echo "âœ… Build completed"
